apiVersion: v1
kind: Service
metadata:
  name: libro-update-service
spec:
  selector:
    app: libro-update
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort 